# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: molecule.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emolecule.proto\x12\x08molecule\x1a\x1cgoogle/protobuf/struct.proto\"\x8a\x01\n\x08Molecule\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03\x64oi\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x1b\n\x0epublished_date\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x12\n\x05title\x18\x04 \x01(\tH\x03\x88\x01\x01\x42\x05\n\x03_idB\x06\n\x04_doiB\x11\n\x0f_published_dateB\x08\n\x06_title\"=\n\x15\x43reateMoleculeRequest\x12$\n\x08molecule\x18\x01 \x01(\x0b\x32\x12.molecule.Molecule\">\n\x16\x43reateMoleculeResponse\x12$\n\x08molecule\x18\x01 \x01(\x0b\x32\x12.molecule.Molecule\"!\n\x13ReadMoleculeRequest\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x14ReadMoleculeResponse\x12$\n\x08molecule\x18\x01 \x01(\x0b\x32\x12.molecule.Molecule\"=\n\x15UpdateMoleculeRequest\x12$\n\x08molecule\x18\x01 \x01(\x0b\x32\x12.molecule.Molecule\">\n\x16UpdateMoleculeResponse\x12$\n\x08molecule\x18\x01 \x01(\x0b\x32\x12.molecule.Molecule\",\n\x15\x44\x65leteMoleculeRequest\x12\x13\n\x0bmolecule_id\x18\x01 \x01(\t\"-\n\x16\x44\x65leteMoleculeResponse\x12\x13\n\x0bmolecule_id\x18\x01 \x01(\t\"\x15\n\x13ListMoleculeRequest\"<\n\x14ListMoleculeResponse\x12$\n\x08molecule\x18\x01 \x01(\x0b\x32\x12.molecule.Molecule\"\x14\n\x12GetMoleculeRequest2\x80\x04\n\x0fMoleculeService\x12U\n\x0e\x43reateMolecule\x12\x1f.molecule.CreateMoleculeRequest\x1a .molecule.CreateMoleculeResponse\"\x00\x12O\n\x0cReadMolecule\x12\x1d.molecule.ReadMoleculeRequest\x1a\x1e.molecule.ReadMoleculeResponse\"\x00\x12U\n\x0eUpdateMolecule\x12\x1f.molecule.UpdateMoleculeRequest\x1a .molecule.UpdateMoleculeResponse\"\x00\x12U\n\x0e\x44\x65leteMolecule\x12\x1f.molecule.DeleteMoleculeRequest\x1a .molecule.DeleteMoleculeResponse\"\x00\x12O\n\x0cListMolecule\x12\x1d.molecule.ListMoleculeRequest\x1a\x1e.molecule.ListMoleculeResponse\"\x00\x12\x46\n\x0bGetMolecule\x12\x1c.molecule.GetMoleculeRequest\x1a\x17.google.protobuf.Struct\"\x00\x62\x06proto3')



_MOLECULE = DESCRIPTOR.message_types_by_name['Molecule']
_CREATEMOLECULEREQUEST = DESCRIPTOR.message_types_by_name['CreateMoleculeRequest']
_CREATEMOLECULERESPONSE = DESCRIPTOR.message_types_by_name['CreateMoleculeResponse']
_READMOLECULEREQUEST = DESCRIPTOR.message_types_by_name['ReadMoleculeRequest']
_READMOLECULERESPONSE = DESCRIPTOR.message_types_by_name['ReadMoleculeResponse']
_UPDATEMOLECULEREQUEST = DESCRIPTOR.message_types_by_name['UpdateMoleculeRequest']
_UPDATEMOLECULERESPONSE = DESCRIPTOR.message_types_by_name['UpdateMoleculeResponse']
_DELETEMOLECULEREQUEST = DESCRIPTOR.message_types_by_name['DeleteMoleculeRequest']
_DELETEMOLECULERESPONSE = DESCRIPTOR.message_types_by_name['DeleteMoleculeResponse']
_LISTMOLECULEREQUEST = DESCRIPTOR.message_types_by_name['ListMoleculeRequest']
_LISTMOLECULERESPONSE = DESCRIPTOR.message_types_by_name['ListMoleculeResponse']
_GETMOLECULEREQUEST = DESCRIPTOR.message_types_by_name['GetMoleculeRequest']
Molecule = _reflection.GeneratedProtocolMessageType('Molecule', (_message.Message,), {
  'DESCRIPTOR' : _MOLECULE,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.Molecule)
  })
_sym_db.RegisterMessage(Molecule)

CreateMoleculeRequest = _reflection.GeneratedProtocolMessageType('CreateMoleculeRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMOLECULEREQUEST,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.CreateMoleculeRequest)
  })
_sym_db.RegisterMessage(CreateMoleculeRequest)

CreateMoleculeResponse = _reflection.GeneratedProtocolMessageType('CreateMoleculeResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEMOLECULERESPONSE,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.CreateMoleculeResponse)
  })
_sym_db.RegisterMessage(CreateMoleculeResponse)

ReadMoleculeRequest = _reflection.GeneratedProtocolMessageType('ReadMoleculeRequest', (_message.Message,), {
  'DESCRIPTOR' : _READMOLECULEREQUEST,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.ReadMoleculeRequest)
  })
_sym_db.RegisterMessage(ReadMoleculeRequest)

ReadMoleculeResponse = _reflection.GeneratedProtocolMessageType('ReadMoleculeResponse', (_message.Message,), {
  'DESCRIPTOR' : _READMOLECULERESPONSE,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.ReadMoleculeResponse)
  })
_sym_db.RegisterMessage(ReadMoleculeResponse)

UpdateMoleculeRequest = _reflection.GeneratedProtocolMessageType('UpdateMoleculeRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMOLECULEREQUEST,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.UpdateMoleculeRequest)
  })
_sym_db.RegisterMessage(UpdateMoleculeRequest)

UpdateMoleculeResponse = _reflection.GeneratedProtocolMessageType('UpdateMoleculeResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMOLECULERESPONSE,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.UpdateMoleculeResponse)
  })
_sym_db.RegisterMessage(UpdateMoleculeResponse)

DeleteMoleculeRequest = _reflection.GeneratedProtocolMessageType('DeleteMoleculeRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEMOLECULEREQUEST,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.DeleteMoleculeRequest)
  })
_sym_db.RegisterMessage(DeleteMoleculeRequest)

DeleteMoleculeResponse = _reflection.GeneratedProtocolMessageType('DeleteMoleculeResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEMOLECULERESPONSE,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.DeleteMoleculeResponse)
  })
_sym_db.RegisterMessage(DeleteMoleculeResponse)

ListMoleculeRequest = _reflection.GeneratedProtocolMessageType('ListMoleculeRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTMOLECULEREQUEST,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.ListMoleculeRequest)
  })
_sym_db.RegisterMessage(ListMoleculeRequest)

ListMoleculeResponse = _reflection.GeneratedProtocolMessageType('ListMoleculeResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTMOLECULERESPONSE,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.ListMoleculeResponse)
  })
_sym_db.RegisterMessage(ListMoleculeResponse)

GetMoleculeRequest = _reflection.GeneratedProtocolMessageType('GetMoleculeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETMOLECULEREQUEST,
  '__module__' : 'molecule_pb2'
  # @@protoc_insertion_point(class_scope:molecule.GetMoleculeRequest)
  })
_sym_db.RegisterMessage(GetMoleculeRequest)

_MOLECULESERVICE = DESCRIPTOR.services_by_name['MoleculeService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MOLECULE._serialized_start=59
  _MOLECULE._serialized_end=197
  _CREATEMOLECULEREQUEST._serialized_start=199
  _CREATEMOLECULEREQUEST._serialized_end=260
  _CREATEMOLECULERESPONSE._serialized_start=262
  _CREATEMOLECULERESPONSE._serialized_end=324
  _READMOLECULEREQUEST._serialized_start=326
  _READMOLECULEREQUEST._serialized_end=359
  _READMOLECULERESPONSE._serialized_start=361
  _READMOLECULERESPONSE._serialized_end=421
  _UPDATEMOLECULEREQUEST._serialized_start=423
  _UPDATEMOLECULEREQUEST._serialized_end=484
  _UPDATEMOLECULERESPONSE._serialized_start=486
  _UPDATEMOLECULERESPONSE._serialized_end=548
  _DELETEMOLECULEREQUEST._serialized_start=550
  _DELETEMOLECULEREQUEST._serialized_end=594
  _DELETEMOLECULERESPONSE._serialized_start=596
  _DELETEMOLECULERESPONSE._serialized_end=641
  _LISTMOLECULEREQUEST._serialized_start=643
  _LISTMOLECULEREQUEST._serialized_end=664
  _LISTMOLECULERESPONSE._serialized_start=666
  _LISTMOLECULERESPONSE._serialized_end=726
  _GETMOLECULEREQUEST._serialized_start=728
  _GETMOLECULEREQUEST._serialized_end=748
  _MOLECULESERVICE._serialized_start=751
  _MOLECULESERVICE._serialized_end=1263
# @@protoc_insertion_point(module_scope)
